apiVersion: v1
kind: Service
metadata:
  name: fon-gitops-api-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: fon-gitops-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080